spring:
  datasource:
    url: jdbc:mysql://inventory-db.cz2is2ei4qrx.ap-southeast-1.rds.amazonaws.com:3306/inventory_db?serverTimezone=Asia/Bangkok
    username: admin
    password: EvREn29PCfNhVv5
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true