ALTER TABLE product
ADD COLUMN code VARCHAR(30) UNIQUE AFTER id,

ADD COLUMN description VARCHAR(500) AFTER name,

ADD COLUMN quantity INT NOT NULL DEFAULT 0 AFTER price,

ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' AFTER quantity,

ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
ON UPDATE CURRENT_TIMESTAMP;